version: '3.4'

services:
  immersionmirror:
    image: ${DOCKER_REGISTRY-}immersionmirror
    restart: always
    build:
      context: .
      dockerfile: ImmersionMirror/Dockerfile
    volumes:
      - ./VideoInput:/app/InDir
      - ./AudioOutput:/app/OutDir
